api_platform:
    title: 'Reservit! API de Reservas de Espacios'
    description: API to manage users, spaces and reservations. Includes JWT authentication.
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
